### ISSUE TITLE
bug: Crash when installed in a secondary user profile

### ISSUE THREAD

**Issue by powerfulsaber** [rhunk/SnapEnhance#219]
### Description

When trying to open Snapchat in a secondary user profile, it crashes after a few seconds. I'm using a non-rooted device, so I used LSPatch and integrated the SnapEnhance module into the app. I also tested running Snapchat in the main user profile and it didn't crash on startup.  

### Reproduction steps

1. Patch the app with LSPatch
2. Install it in a secondary profile
3. Open Snapchat

### Logs

```markdown
I'm not able to use logcat while in a secondary profile. I can at times see a pop-up that says "Show details" that would show the logs, but the app crashes too quickly for it to appear.
```

### Snapchat Version

12.39.0.48, 12.44 0.59, 12.48.1.0, 12.48.0.66

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
can't reproduce

**Comment by Robotition** [comment]
This is a bug that occurs specifically on GrapheneOS and it would need to be properly implemented on the module for it to support GrapheneOS

**Comment by authorisation** [comment]
> This is a bug that occurs specifically on GrapheneOS and it would need to be properly implemented on the module for it to support GrapheneOS

How exactly? We don't have any GrapheneOS devices on hand right now, feel free to make a PR

**Comment by Robotition** [comment]
I don't have experience in development, however I can help with testing since I have a device with GrapheneOS and provide logs

**Comment by authorisation** [comment]
You mentioned it needed proper implementation, what exactly made you think that?

**Comment by authorisation** [comment]
Provide logs on the crash with LSPatch

**Comment by authorisation** [comment]
LSPosed definitely does not GrapheneOS as explained here:
https://github.com/LSPosed/LSPosed/issues/2481#issuecomment-1501243597

**Comment by Robotition** [comment]
Here is logcat: [logcat.txt](https://github.com/rhunk/SnapEnhance/files/13625896/logcat.txt)
Here is crash log snapchat left: [snapchat_crash.txt](https://github.com/rhunk/SnapEnhance/files/13625897/snapchat_crash.txt)

Let me know if it's something that you can fix or if it's a LSPatch issue.

**Comment by authorisation** [comment]
Yeah there's pretty much nothing we can do about this

**Comment by Robotition** [comment]
Alright, thank you for letting me know. Will open an issue about this in LSPatch

**Comment by authorisation** [comment]
Let us know how it goes, we'll keep this open for now.

**Comment by Robotition** [comment]
Hello, in the Telegram group someone figured out how to get SnapEnhance working on GrapheneOS.
Credit goes to Michael E. on Telegram: https://t.me/snapenhance_chat/1/30346
Here is the full guide:
GrapheneOS SnapEnhance install guide 
Environment:
     GrapheneOS
     Pixel 5
     Snapchat v12.64.0.42
     Snapenhance 2.0.0
     Lucky patcher
     No root
     LSPatch v0.6 ----- NEEDS TO HAVE EXPLOIT PROTECTION COMPATABILITY MODE ENABLED

Steps taken:
     Luckypatcher patch 
          Signature verification killer
     Copy patched apk out of luckypatcher directory
     LSPatch 
          Local
          Signature bypass lv0  (lv2 will crash)
          Install and run
This is a rough guide, as I wrote it in google notes, it could be improved for easier readability.

Also make sure to only use Signature killer patch and nothing else otherwise it won't work.

**Comment by Robotition** [comment]
I would recommend putting this guide in the readme for other GrapheneOS users

**Comment by TheVisual** [comment]
@rhunk @authorisation https://github.com/LSPosed/LSPatch is now Archived best to close this

**Comment by authorisation** [comment]
Closed for now :)
