### ISSUE TITLE
Friend Tracker

### ISSUE THREAD

**Issue by admi-netizen** [rhunk/SnapEnhance#275]
### Description

Recieve notification when specified user score changes (for spam limit it every 5mins or so, or dont i dont mind)

This combined with "No friend score delay" that logs every DD.MM.YY/HH:MM:SS of +1 point or so in log file.

Seeing your friend score go up after you open your snap is awesome, works wonders.
But i would like to check it by myself in log file at what times it went up ;)

Snapchat score is unreliable , but "No friend score delay" really makes that a bit more reliable and true.

Man i would pay for this feature. Thanks very much great community and project.!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Halua0sS** [comment]
Why I can't see snap enhance new version (ver 12)

**Comment by RSR1337** [comment]
I have tried 4abe3c7

But it still displays the username instead of the display name, and also Bitmoji does not display the correct one

![Screenshot_2024-04-20-21-13-32-91_48a5d58b88b9b42ec8234f53f7b8fcd2](https://github.com/rhunk/SnapEnhance/assets/52901789/2517f3f1-1b52-4074-b1c4-5fed2ec15103)

They already have Bitmoji

**Comment by RSR1337** [comment]
> This is already looking quite nice. Does this allow you to get notifications too?

Yes
