### ISSUE TITLE
feat: Story Logger

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#406]
### Description

Would be interesting to see a story logger implemented, for example if someone posts something then deletes it, it would still be accessible by clicking their profile or stories page, but it would have some sort of overlay (maybe could replace the reply text) saying when it was posted and deleted.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/614d629f07f84d3ac51294b915f3f517fedadb80

**Comment by xnvmx** [comment]
Hi, I have the previous version, without the story logger.
If I install new version with this enhancement, will it be possible to recover a story that disappeared 2 hours ago? Or maybe there is another way? I really need this story...

**Comment by rhunk** [comment]
@xnvmx Unfortunately there is no way to recover a story that has been deleted without first using the mod

**Comment by xnvmx** [comment]
@rhunk I have one more question, how to export these stories? This is saved in a .db file, but how to open it and export stories to .jpg and .mp4 files?

**Comment by xnvmx** [comment]
@rhunk My SnapEnhance app crashes when I try to open dozens of logged stories from one friend.
When I try to open only one logged story from another friend, it works fine. 
How to fix it?

**Comment by rhunk** [comment]
@xnvmx got fixed already https://github.com/rhunk/SnapEnhance/commit/1241d68d3cacb114540b0624612ca4f0855a5bf9

**Comment by xnvmx** [comment]
> @xnvmx got fixed already [1241d68](https://github.com/rhunk/SnapEnhance/commit/1241d68d3cacb114540b0624612ca4f0855a5bf9)

There is any possibility to update the beta version of SnapEnhance without losing data? 
I would like to keep logged messages, stories and everyone else.
Theoretically, there is an option to export to a db file, but I don't see an import option anywhere.
I don't want to lose it, because it happened recently when I installed a new version.

**Comment by rhunk** [comment]
@xnvmx The best solution right now is to root your device and install CorePatch to update over the existing version.
But you can still save the exported db, as this feature will be implemented in the message logger history.

**Comment by xnvmx** [comment]
@rhunk Either I'm doing something wrong or this story logger doesn't do its job at all... 

In the SnapEnhance settings it shows that the appropriate number of stories are saved, but when I go to "Show Logged Stories" - it only shows some of these stories, and some of them take forever to load. Instead, there are spinning wheels and when I try to save it says: "Failed to get file" or "Failed to download". In turn, the ones that are displayed are still available to see normally in Snapchat, because they simply haven't disappeared yet or I saved them in the chat. 

So I don't understand why this function "Show logged stories" and whole Story Logger exists if it only displays stories that have not disappeared yet or have been saved in the chat. 
I hope I'm doing something wrong, because two very important stories have disappeared, leaving behind this spinning circle and the date of creation and posting, nothing else...

https://github.com/rhunk/SnapEnhance/assets/92065189/a41c8b3b-38bf-4132-b36e-cd972058c22e

**Comment by xnvmx** [comment]
@rhunk Either I'm doing something wrong or this story logger doesn't do its job at all... 

In the SnapEnhance settings it shows that the appropriate number of stories are saved, but when I go to "Show Logged Stories" - it only shows some of these stories, and some of them take forever to load. Instead, there are spinning wheels and when I try to save it says: "Failed to get file" or "Failed to download". In turn, the ones that are displayed are still available to see normally in Snapchat, because they simply haven't disappeared yet or I saved them in the chat. 

So I don't understand why this function "Show logged stories" and whole Story Logger exists if it only displays stories that have not disappeared yet or have been saved in the chat. 
I hope I'm doing something wrong, because two very important stories have disappeared, leaving behind this spinning circle and the date of creation and posting, nothing else...


https://github.com/rhunk/SnapEnhance/assets/92065189/9b40d77b-8715-4f2b-b59a-5ee1a34d5aa2

**Comment by rhunk** [comment]
@xnvmx Snapchat deletes server-side media that has only been sent as a story by the sender when it expires. It is therefore normal that you will no longer be able to access them.

**Comment by xnvmx** [comment]
@rhunk So why isn't it saved locally on the device, I thought that was the intention of this add-on.
Because since it is deleted practically at the same time as the story disappears, it is a bit pointless.

A good solution would be to save locally permanently or for a specific period of time, e.g. a week or a month.


BTW So I understand that it is no longer possible to recover the stories I was talking about? They expired only 10 hours ago, I have the date and time when they were created and posted from the Story Logger, maybe there is a way?

**Comment by xnvmx** [comment]
@rhunk So why isn't it saved locally on the device, I thought that was the intention of this add-on.
Because since it is deleted practically at the same time as the story disappears, it is a bit pointless.

A good solution would be to save locally permanently or for a specific period of time, e.g. a week or a month.

BTW Does it mean that it is no longer possible to recover the stories I was talking about? They expired only 10 hours ago, I have the date and time when they were created and posted from the Story Logger, maybe there is a way?

**Comment by xnvmx** [comment]
@rhunk So why isn't it saved locally on the device, I thought that was the intention of this add-on.
Because since server-side media is deleted practically at the same time as the story disappears, it is a bit pointless.

A good solution would be to save locally permanently or for a specific period of time, e.g. a week or a month.

BTW Does it mean that it is no longer possible to recover the stories I was talking about? They expired only 10 hours ago, I have the date and time when they were created and posted from the Story Logger, maybe there is a way?

**Comment by rhunk** [comment]
@xnvmx The main purpose of this feature is to be able to view stories that have been deleted, not necessarily those that have expired, like the message logger.

In your case, the URL of the media is no longer available, it would appear to be impossible to retrieve it.
