### ISSUE TITLE
feat: quick enable stealth mode

### ISSUE THREAD

**Issue by NotApex** [rhunk/SnapEnhance#497]
### Description

~~A little icon on/next to the text bar where you can enable stealth mode quickly without having to use the context menu~~ **Cannot be implemented for compatibility and ergonomic reasons in the FF**

~~when someone sends you a snap you can have a notification option to reply with a black snap kinda like black photos~~ **Automatic sending of messages will never be supported officially**

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Not-Smelly-Garbage** [comment]
Would be interesting to see implemented, there could be a setting in the snapenhance app that enables you to toggle different added ui elements from in chats. Such as merge overlay, autosave etc.
I guess its possible by long pressing the chat (except merge overlays) it could be a quick alternative.

Having the merge overlay option easier to access would be helpful when downloading snaps, because sometimes you might want to keep overlays for some videos and some not. Would be easier to switch it that way

Im not a dev, just adding suggestions to this suggestion lol
