### ISSUE TITLE
feat: Spoof Only Sent To You (Fidelius?) status on snaps

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#559]
### Description

Can you please add an option where we can spoof whether a snap was or wasn't sent to multiple people? This should allow us both to turn it off if it was and on if it wasn't.
Thank you!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Impossible because snaps can only be encrypted to one person in dm and if you want to remove the encryption you can add a dummy account as recipient

**Comment by CompuGenius** [comment]
> Impossible because snaps can only be encrypted to one person in dm and if you want to remove the encryption you can add a dummy account as recipient

Well, I'm not sure what Fidelius is, but I don't need encryption, I was actually just hoping for a way to bypass SnapEnhance's own detector of snaps being sent to one or multiple people, in case someone is using it "against" me or similar.

**Comment by sestuff** [comment]
> > Impossible because snaps can only be encrypted to one person in dm and if you want to remove the encryption you can add a dummy account as recipient
> 
> Well, I'm not sure what Fidelius is, but I don't need encryption, I was actually just hoping for a way to bypass SnapEnhance's own detector of snaps being sent to one or multiple people, in case someone is using it "against" me or similar.

What I think he means is that the Fidelius feature works by checking if the snap was encrypted or not. Snapchat only encrypts snaps sent to one person, but if it's sent to more than one person it isn't encrypted since they don't want to make multiple files for each recipient (you can't encrypt a file with keys from two different recipients, so there would need to be files for each).

That being said, a feature could be implemented to hook the send event and make individual requests for each recipient instead of one for all of them, but it would require more work than it's worth. Just send a photo from gallery and use the override media type option so you can send the same "snap" individually to multiple people (you can also just save the snap to gallery from snapchat).
