### ISSUE TITLE
How can I quickly update the Snapchat app version? 

### ISSUE THREAD

**Issue by agarfa433** [rhunk/SnapEnhance#632]
### Description

I've been uninstalling the entire Snapchat app and then reinstalling it lately and I don't know if that's the right way to do it..? 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.57.0.55

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by sestuff** [comment]
So basically in order to update an app instead of uninstalling it + reinstalling it, the app needs to be signed with a certificate. The issue is that Snapchat checks the signature and if it doesn't match their legitimate one it won't work, so it has to be left unsigned. Since it's unsigned, the app can't be updated therefore requiring reinstallation. There were ways around this (you can ask in https://t.me/snapenhance_chat), but I'm not sure if they still work.
